name: inline_rich_text_span
description: "This package provides InlineRichTextSpanWidget, a convenient wrapper around Flutter's RichText core. It's designed to make constructing complex text layouts with multiple styles more straightforward by accepting InlineSpans directly in its children list."
version: 0.0.1
homepage: none

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
